---
title: "ClimateChange"
author: "Jack Grafton"
date: "3/6/2018"
output: html_document
---

##Introduction

##Methods

##Results


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r LoadData}
USTemp<- readRDS("USAAnnualTemp1950_2008.rds")
USPcpn<- readRDS("USAAnnualPcpn1950_2008.rds")
```


```{r CleanData}
AnnualTempState <- aggregate(data ~ year+state, USTemp, mean)
AnnualPcpnState <- aggregate(data ~ year+state, USPcpn, mean)

AnnualTempState$decade <- cut(AnnualTempState$year, breaks=c(1950,1960,1970,1980,1990,2000,2008,2010), labels=c(1950,1960,1970,1980,1990,2000,2008), 
                              include.lowest=TRUE, right=FALSE)
DecadalTempState <- aggregate(data ~ decade+state, data=AnnualTempState, mean)


AnnualPcpnState$decade <- cut(AnnualPcpnState$year, breaks=c(1950,1960,1970,1980,1990,2000,2008,2010), labels=c(1950,1960,1970,1980,1990,2000,2008), 
                       include.lowest=TRUE, right=FALSE)
DecadalPcpnState <- aggregate(data ~ decade+state, data=AnnualPcpnState, mean)

```

